### ISSUE TITLE
Error with tm_shape

### ISSUE THREAD

**Issue by SteveM49** [Robinlovelace/Creating-maps-in-R#33]
While trying to rerun code in intro_spatial.Rmd I found an error while executing near line 1106.  The error message was:
The argument drop.shapes has been renamed to drop.units, and is therefore deprecated
 Hide Traceback
Error in plot_all(1, list(tmLayer1 = list(npol = 33L, varnames = list( : object 'treeMapX' not found
10.
plot_all(1, structure(list(tmLayer1 = structure(list(npol = 33L, varnames = structure(list(by = c("Barking and Dagenham", "Barnet", "Bexley", "Brent", "Bromley", "Camden", "City of London", "Croydon", "Ealing", "Enfield", "Greenwich", "Hackney", "Hammersmith and Fulham", ...
9.
do.call(fun, args = list(1, gp_leg[[k]], gal, shps, dasp, sasp, inner.margins.new, legend_pos, nx > 1))
8.
cellplot(gmeta$legy, gmeta$legx, e = do.call(fun, args = list(1, gp_leg[[k]], gal, shps, dasp, sasp, inner.margins.new, legend_pos, nx > 1)), name = "outside_legend")
7.
gList(cellplot(gmeta$legy, gmeta$legx, e = do.call(fun, args = list(1, gp_leg[[k]], gal, shps, dasp, sasp, inner.margins.new, legend_pos, nx > 1)), name = "outside_legend"))
6.
FUN(X[[i]], ...)
5.
lapply(1:np, function(k) { if (k != 1) { grid.newpage() } ...
4.
gridplot(gm, "plot_all", nx, g$gps, gal, shps, gm$shape.dasp, gm$shape.sasp, gm$shape.inner.margins, gm$shape.legend_pos, g$gp_leg, g$gp_attr)
3.
print_tmap(x = x, vp = vp, return.asp = return.asp, mode = mode, show = show, knit = knit, options = options, ...)
2.
print.tmap(x)
1.
function (x, ...) UseMethod("print")(x)
----------------------
I tried the obvious change of renaming drop_shapes, but then it complained of an xTree problem.
--------------------------

This is the first time I have reported an issue for anything in github.  If I have made a technical or social error, please let me know.
stevemaguire@gmail.com

**Comment by Robinlovelace** [comment]
Hi Steve, no you've not made an error - there is a definite problem now that **tmap** has evolved.

Thanks for reporting!
