### ISSUE TITLE
data types and structures.

### ISSUE THREAD

**Issue by koyo-jakanees** [Robinlovelace/Creating-maps-in-R#52]
Hi @Robinlovelace  thank you guys for this great treasure. 
It would be extremely fab if you included/added like a chapter introducing the basic data types like strings, bool, int,  array, and function syntax in brief(the most important ones at least) so that absolutely new beginners who are specifically interested in Rspatial would much simpler following through.
Honestly i had to go through other tut which i wasn't really interested in.

Thank you.
Davince

**Comment by koyo-jakanees** [comment]
Hi Robin
yes sure a link to another resource would be appreciated.
Only opened this issue as a suggestion.
so that one doesn't have to go to other resources to understand the basics of R then deep dive to spatial R.(i mean a lil bit of R structure) if you want to try out something real quick..
thanks.

**Comment by Robinlovelace** [comment]
Thanks for the input and yes, perhaps it would be worth adding something on data types here - feel free to put in a pull request adding a 'lil bit' on data types, I'd be happy to review it and most likely accept it.Thanks!
